### ISSUE TITLE
Selecting "Edit label" crashes Rack [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [jimallman/interrobang-rack-modules#2] opened 2020-03-30 03:11 UTC
[25.276 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
21: ZN4rack10appDestroyEv 0x456d75
20: raise 0x2686ac70
19: abort 0x2686f270
18: assert 0x2686b510
17: osdialog_prompt 0x4a9812
16: ZN19ScribbleStripWidget20ScribbleEditMenuItem8onActionERKN4rack5event6ActionE 0xe9b34c0
15: ZN4rack2ui8MenuItem8doActionEv 0x4a4f1e
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x458008
13: ZN4rack7updater17isUpdateAvailableEv 0x459a8e
12: glfwPlatformUnlockMutex 0x4d7e2e
11: DispatchMessageW 0x25e86e30
10: CallWindowProcW 0x25e86d30
9: glPushClientAttrib 0x9b11490
8: DispatchMessageW 0x25e86e30
7: DispatchMessageW 0x25e86e30
6: glfwPlatformPollEvents 0x4db4e6
5: ZN4rack6Window3runEv 0x459e86
4: main 0x7838a0
3: main 0x7838a0
2: main 0x7838a0
1: BaseThreadInitThunk 0x25837960
0: RtlUserThreadStart 0x282da240

**Comment by SteveRussell33** [comment] 2020-03-30 03:12
[25.276 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
21: ZN4rack10appDestroyEv 0x456d75
20: raise 0x2686ac70
19: abort 0x2686f270
18: assert 0x2686b510
17: osdialog_prompt 0x4a9812
16: ZN19ScribbleStripWidget20ScribbleEditMenuItem8onActionERKN4rack5event6ActionE 0xe9b34c0
15: ZN4rack2ui8MenuItem8doActionEv 0x4a4f1e
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x458008
13: ZN4rack7updater17isUpdateAvailableEv 0x459a8e
12: glfwPlatformUnlockMutex 0x4d7e2e
11: DispatchMessageW 0x25e86e30
10: CallWindowProcW 0x25e86d30
9: glPushClientAttrib 0x9b11490
8: DispatchMessageW 0x25e86e30
7: DispatchMessageW 0x25e86e30
6: glfwPlatformPollEvents 0x4db4e6
5: ZN4rack6Window3runEv 0x459e86
4: main 0x7838a0
3: main 0x7838a0
2: main 0x7838a0
1: BaseThreadInitThunk 0x25837960
0: RtlUserThreadStart 0x282da240

**Comment by jimallman** [comment] 2020-03-30 04:34
Thanks for this report! I have a Mac with VMWare Fusion, but it's running Windows 8.1 Pro. Still, I'll see if I can reproduce this behavior. (Are there any known issues with `osdialog_prompt` on Windows?)

**Comment by jimallman** [comment] 2020-03-30 04:42
> Are there any known issues with `osdialog_prompt` on Windows?

Looks like this might [still not be](https://github.com/cfoulc/cf/issues/33#issuecomment-516460922) implemented [on Windows](https://community.vcvrack.com/t/is-there-a-portable-way-to-open-a-pop-up-window/6573/2). Hmm, maybe I can revise the UI to prompt for text in a submenu.

**Comment by SteveRussell33** [comment] 2020-03-30 05:06
Check out how David does this for his TD202 vertical text display module.
https://github.com/david-c14/SubmarineFree/blob/master/src/TD2.cpp

**Comment by Petervos2018** [comment] 2020-03-31 23:36
Came here for the same reason, might as well post the log part, but I think you already know what's going on.
Wanted to use this because it can flip the text bottom to top, that feels more natural than top to bottom.(hurts my neck)

And the winning numbers are : 

[21.247 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
21: ZN4rack10appDestroyEv 0x456435
20: raise 0x99acac60
19: abort 0x99acf270
18: assert 0x99acb510
17: osdialog_prompt 0x4a9292
16: ZN19ScribbleStripWidget20ScribbleEditMenuItem8onActionERKN4rack5event6ActionE 0x9f334c0
15: ZN4rack2ui8MenuItem8doActionEv 0x4a49ae
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0x98765850
10: CallWindowProcW 0x98765850
9: glPushClientAttrib 0x86673770
8: CallWindowProcW 0x98765850
7: DispatchMessageW 0x98765410
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x99b57bc0
0: RtlUserThreadStart 0x99caceb0

**Comment by jimallman** [comment] 2020-04-01 17:22
> Check out how David does this for his TD202 vertical text display module.

Very nice. Now I just need to grok nanovg, blendish, and how they're used to manage cursor placement, text metrics, etc. Rack is not for the faint of heart! (Any pointers to high-level documentation on all these dependencies would be appreciated.)

**Comment by jimallman** [comment] 2020-04-04 06:24
@SteveRussell33 I believe this is fixed, so I'm going to re-submit this plugin. Should I close this, or would you rather?

**Comment by SteveRussell33** [comment] 2020-04-04 18:55
I now get this error building master branch:
```
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/ScribbleStrip.cpp.o src/ScribbleStrip.cpp
src/ScribbleStrip.cpp:95:8: error: 'function' in namespace 'std' does not name a template type
   95 |   std::function<void(std::string)> changeHandler;
      |        ^~~~~~~~
src/ScribbleStrip.cpp:3:1: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?
    2 | #include "osdialog.h"
  +++ |+#include <functional>
    3 |
src/ScribbleStrip.cpp: In member function 'virtual void ScribbleStripWidget::EventParamField::onSelectKey(const rack::event::SelectKey&)':
src/ScribbleStrip.cpp:107:9: error: 'changeHandler' was not declared in this scope
  107 |     if (changeHandler) {
      |         ^~~~~~~~~~~~~
src/ScribbleStrip.cpp: In member function 'virtual void ScribbleStripWidget::appendContextMenu(rack::ui::Menu*)':
src/ScribbleStrip.cpp:133:14: error: 'struct ScribbleStripWidget::EventParamField' has no member named 'changeHandler'
  133 |   editField->changeHandler = [=](std::string text) {
      |              ^~~~~~~~~~~~~
make: *** [../../compile.mk:69: build/src/ScribbleStrip.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
```

I edited ScribbleStrip.cpp:
```
#include <functional>
```
and removed the osdialog include, it now compiles.

Tested the module in Rack and no longer crashes. I'll leave this open for now for any comment as it's not really GitHub etiquette to reply to closed issues.

**Comment by jimallman** [comment] 2020-04-04 21:09
Thanks! That wasn't needed on my Mac, which I suppose is using a more recent version of C++.

I'm including this now, and added a minor cleanup of the `changeHandler`. Still compiles and works for me locally.

**Closed as completed by jimallman** 2020-04-04 21:09 UTC
